# Usa a imagem do Microsoft OpenJDK 21 como base
FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas os arquivos necessários para cache das dependências
COPY mvnw pom.xml ./
COPY .mvn .mvn
RUN ./mvnw dependency:go-offline

# Copia o código-fonte da aplicação
COPY src src

# Expõe a porta da aplicação
EXPOSE 8080

# Comando para rodar a aplicação no modo desenvolvimento
CMD ["./mvnw", "spring-boot:run"]