services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}:postgres"
      POSTGRES_PASSWORD: "${DB_PASS}:passw"
      POSTGRES_DB: "${DB_NAME}:crudjavapostgres"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - .:/app
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://`${DB_HOST}:5432/${DB_NAME}`

volumes:
  db-data: